#!/bin/bash
cd ~/Documents/code/c++/passwords
while getopts ":s:l:f:har:" selector; do
	case $selector in
		s)
			./short "$OPTARG"
			;;
		l)
			./long "$OPTARG"
			;;
		f)
			less ~/Dropbox/passwords.txt | grep -A 1 "$OPTARG"
			;;
		a)
			less ~/Dropbox/passwords.txt
			;;
		h)
			echo "	-s : generate a normal-length password"
			echo "	-l : generate a longer password made of3 random words strung together"
			echo "	-f : search for a specific password"
			echo "	-a : list all passwords. a fallback for -f"
			;;
		r)
			echo "$3"
			./random "$2" "$3"
			;;
		\?)
			
	esac
done
./sort
if [[ $(diff passwords.txt ~/Dropbox/passwords.txt) ]]; then
	./fix
fi

if [[ $(wget http://www.google.com -o /dev/null ) ]]; then
	cp passwords.txt ~/Dropbox/passwords.txt
	echo "copied the file"
else
	echo "Will copy the file when connected to the internet again"
fi

cd - 2>&1 >/dev/null